---
title: "About the Project - Background Information"

output: html_document
---
<br>

*Some additional information regarding the nature of our outcomes of interest.*

<br>

**Severe Maternal Morbidity** 

Maternal morbidity is defined by the WHO as "any health condition attributed to and/or aggravated by pregnancy and childbirth that has a negative impact on the woman’s well-being”. The medical causes of morbidity include hemorrhaging and pregnancy related infections, induced abortions, and complications during labor. Outside of these medical factors, there are many socioeconomic determinants to rates of maternal morbidity within a population. According to literature these most often include access to quality maternal health services, both during pregnancy and during labor. Access may come in the form of health insurance, proximity to reproductive health care facilities, and quality of care available at health care facilities [1](https://www.ncbi.nlm.nih.gov/books/NBK361917/). In New York City, racial and ethnic disparities have contributed significantly to high rates of maternal morbidity. According to a study published in the Maternal and Child Health Journal, SMM rates were high among black, non-latina women in particular. Maternal education, income, and lack of prenatal care were also significantly associated with SMM [2](https://link-springer-com.ezproxy.cul.columbia.edu/article/10.1007/s10995-018-2682-z).  

**Preterm Births**

Preterm birth is defined as the live birth of an infant prior to 37 weeks of gestation, with the categories of late preterm at 34-36 weeks, moderately preterm at 32-36 weeks, and very preterm at less than 32 weeks [1](https://www.marchofdimes.org/peristats/ViewTopic.aspx?reg=36&top=3&lev=0&slev=4). In addition to putting babies at risk of underdevelopment of vital organs, preterm births also affect maternal health by increasing the mother’s risk of developing postnatal physical health problems, depression, and lower usage of postnatal support [2](https://bmjopen.bmj.com/content/6/10/e012676), [3](https://www.frontiersin.org/articles/10.3389/fpubh.2018.00359/full). Racial and ethnic disparities exist in preterm birth rates across the nation, with the highest rates of preterm births among African-American mothers (14.4%) that are almost 50% higher than the rates among white (9.3%) or Hispanic (10%) women in 2019 [4](https://www.cdc.gov/reproductivehealth/maternalinfanthealth/pretermbirth.htm). In NYC, the overall rate of preterm births was 9.0% in 2017. When categorized by race, the preterm birth rate was 12.7% among Black women, 9.6% among Hispanic women, 7.9% among Asian women, 6.9% among White women, and 9.9% among women of Other race [5](https://data.cccnewyork.org/data/table/1276/preterm-births#1277/1480/25/a/a). While there are multiple risk factors for preterm birth including previous preterm births, pregnancy with multiples, tobacco and substance usage, short durations between pregnancies, and pregnancy complications, the socioeconomic environment of the mother is also important [6](https://www.cdc.gov/reproductivehealth/features/premature-birth/). In a 2008 International Journal of Epidemiology report, maternal educational level was found to be the strongest predictor for preterm birth out of five socioeconomic factors, more so than income and occupation [7](https://watermark.silverchair.com/dyn112.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAApwwggKYBgkqhkiG9w0BBwagggKJMIIChQIBADCCAn4GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMTy4eP8rA23acKExiAgEQgIICT7nfOcXpJt31qdbBKOIboYVrwnd_WHQhBeR2zPtf2_4u3bePmf8VV6qV0fEXrHgXvb3N2XB4sesbpMG_2si0irr_CROVEu1ViSWoRkPfTWYpg4tzoXjDr6sR8yZBM-Ka_4WEOclHYN3-guKHuT5Xtrm0cLFG4dcV8cv8xodawfaFfug75W9choeMXMKMea9ndCCyFL0xUuMLS16cXGVHSYzSixgj2MK1vDWLB-jt973iC34bxIBwwTP39ibenmDoH5qD8g6KphGfp8V5ANpwJofRkzYf3CKu9PbMeQzEqOOmTfShwfSn0Wi7jeR8Q37ZwznMKHiFrChO5ndZ46cTAY6az5Dw-ryrQP-S7yOK8t_M9a90Tcj6sUmhsie3WusXcASh_tlI2NySIF7sqMGjWuo_tybivPEpyxjpZUaNd-zaXLmI_wXbhtFWv4UsxzOVi8xG82P3BfvqImmsdkKJT2K28fC6qdBU5ee1Jo7jwXAEtAFpa262U5O1x64gQr76VZ15Z3QSQvYnG6YuJBjq1U3PGYN6svysasziSMNghnwNFgKZroCkWoyv2xe_FBKBP5Ju9Wt5ivOzkT9TLKlfw1n70UmqImeO4CQpdIYafasooL4ijLl_el-A7f5RvP_T9hvdAJ-7Sm-iI_c93luRWtsFJ46JDh4fkADgPRRp41ktocLFPP1KnHxE_diJbS-GscLBxE6jlxRsk8VdObQldz_VSoHw4lRQS0R05dbxcvlVtURdqJeAj8hXgtJLvmCPt9zaErgQZTaDO9bKlxJ8yQ). System-level factors are also seen to affect preterm birth, including the amount of prenatal care, management of maternal chronic disease, and health insurance coverage [8](https://www.tandfonline.com/doi/full/10.1080/10796126.2016.1254601). 

**Gonorrhea**

STI transmission and prevention is a big part of reproductive health. Gonorrhea in particular is a sexually transmitted infection that affects both men and women. It causes infections in the genitals, rectum, and throat and is treatable with antibiotics. While it is a sexually transmitted disease, gonorrhea can also be spread from mother to child during childbirth [1](https://www.cdc.gov/std/gonorrhea/stdfact-gonorrhea.htm). New York City has one of the highest rates of gonorrhea infections in the United States and this rate has almost doubled between 2010 and 2017. In 2017, there were 23,491 cases reported in NYC which was a 23.4% increase from 2016. In part, this is due to an increased use of pre-exposure prophylaxis which has led to decreased condom use. This behavior change has allowed other STI's, like gonorrhea, to increase [2](https://www.politico.com/states/new-york/albany/story/2018/09/25/in-nyc-gonorrhea-chlamydia-cases-up-syphilis-down-625004#:~:text=There%20were%2023%2C491%20cases%20of,percent%20from%20the%20prior%20year.). Despite these increasing trends, most of the new cases are amongst men, not women [3](https://www.health.ny.gov/statistics/diseases/communicable/std/docs/sti_surveillance_report_2017.pdf). At a national level, rates of gonorrhea remain highest among the black population (7.7 times the rate amongst the white population in 2018) [4](https://www.cdc.gov/std/stats18/STDSurveillance2018-full-report.pdf). Overall, there is not a great body of literature that shows population level relationships, instead trends are focused at the individual level.  

<br>
