---
title: "Exploratory Analysis of Preterm Births Outcome"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(readxl)
library(readr)
library(plotly)

knitr::opts_chunk$set(
	fig.width = 9, 
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

  
```{r, include = FALSE}
plots_df = read_csv("./data/final_regression_variables_clean.csv") %>%
    mutate(poverty_level = cut(poverty, breaks = c(-Inf, 10, 20, 30, 40, Inf), labels = c("poverty_10","poverty_20", "poverty_30", "poverty_40", "poverty_40+"))) %>% 
  pivot_longer(
   cols = hispanic:other_race,
   names_to = "race",
   values_to = "percent_pop",
   values_drop_na = TRUE
 ) 
```

The following plots are an exploration of the relationship between various predictors and the outcome of preterm births.

#### Plot 1: Health Insurance and Preterm Births

```{r}
preterm_ggplot = 
  plots_df %>% 
  ggplot(aes(x = health_ins, y = preterm_births), group = nta_name) +
  geom_point(color = "blue") + 
  labs(
    title = "Exploration of Health Insurance and  Preterm Births in NYC Neighborhoods",
    x = "Percent Population with Health Insurance",
    y = "Percent Preterm Births Among All Live Births")

ggplotly(preterm_ggplot)
```



#### Plot 2: Medicaid and Preterm Births

```{r}
preterm2_ggplot = 
  plots_df %>% 
  ggplot(aes(x = medicaid_enroll, y = preterm_births, group = nta_name)) + 
  geom_point(color = "blue") + 
  labs(
    title = "Exploration of Medicaid Enrollment and  Preterm Births in NYC Neighborhoods",
    x = "Percent Population Enrolled in Medicaid",
    y = "Percent Preterm Births Among All Live Births")

ggplotly(preterm2_ggplot)
```



#### Plot 3: Prenatal Care and Preterm Births 

```{r}
prenatal_care_ggplot = 
  plots_df %>% 
  ggplot(aes(x = late_no_prenatal_care, y = preterm_births, group = nta_name)) + 
  geom_point(color = "blue") + 
  labs(
    title = "Exploration of Access to Prenatal Care and  Preterm Births in NYC Neighborhoods",
    x = "Percent Live Births Recieving Late or No Prenatal Care",
    y = "Percent Preterm Births Among All Live Births")

ggplotly(prenatal_care_ggplot)
```